config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resources :habits do
    resources :reminders
    resources :logs, only: [:new, :create, :index, :edit, :update, :destroy]
    resources :calendars, only: [:create]

    member do
      post 'mark_as_current'
      get 'calendars' 
    end
  end

  #  resources :calendars, only: [:create]
end

app/models/reminder.rb
class Reminder < ApplicationRecord
    belongs_to :habit
    belongs_to :user
  
  
    enum frequency: {
      morning: 'Morning',
      afternoon: 'Afternoon',
      evening: 'Evening'
    }
    has_one :calendar, as: :eventable
  end
  

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
    before_action :set_habit
    before_action :set_reminder, only: [:show, :edit, :update, :destroy]
  
    def index
      @reminders = @habit.reminders
    end
  
    def show
    end
  
    def new
      @reminder = Reminder.new
    end
  
    def create
        # @reminder = @habit.reminders.new(reminder_params)
        @habit = Habit.find(params[:habit_id])
        @reminder = @habit.reminders.build(reminder_params)
        @reminder.user = current_user
      
        if @reminder.save
          redirect_to habit_reminder_path(@habit, @reminder), notice: 'Reminder was created.'
        else
            puts @reminder.errors.full_messages
          render :new
        end
      end
  
    def edit
    end
  
    def update
      if @reminder.update(reminder_params)
        redirect_to habit_reminders_path(@reminder.habit), notice: 'Reminder was updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @reminder.destroy
      redirect_to habit_reminders_path(@habit), notice: 'Reminder was deleted.'
    end
  
    private
  
    def set_habit
      @habit = Habit.find(params[:habit_id])
    end
  
    def set_reminder
      @reminder = Reminder.find(params[:id])
      @reminder = @habit.reminders.find(params[:id])
    end
  
    def reminder_params
      params.require(:reminder).permit(:user_id, :frequency, :habit_id, :calendar_date, :description)
    end
  end
  

app/views/reminders/_form.html.erb
<%= form_with model: [@habit, @reminder] do |form| %>
 
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :frequency %>
    <%= form.select :frequency, Reminder.frequencies.keys.map { |f| [f.humanize, f] } %>
  </div>

  <div class="field">
    <%= form.label :habit_id %>
    <%= form.collection_select(:habit_id, Habit.all, :id, :name, prompt: 'Select a habit') %>
  </div>

  <div class="field">
    <%= form.label :calendar_date %>
    <%= form.date_field :calendar_date %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Reminder' %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<%= form_with model: [@habit, @reminder], local: true do |form| %>
    <h1>Edit Reminder</h1>

    <%= render "form", reminder: @reminder %>

    <%= link_to 'Back', habit_reminders_path %>
    <%= form.submit 'Update Reminder' %>
  <% end %>
  

app/views/reminders/index.html.erb
<h1>Reminders</h1>

<table class="table">
  <thead>
    <tr>
      <th>Habit</th>
      <th>Frequency</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td>
          <%= link_to reminder.habit.name, habit_path(reminder.habit) %>
        </td>
        <td>
          <%= reminder.frequency %>
        </td>
        <td>
          <%= link_to 'Edit', edit_habit_reminder_path(reminder.habit, reminder), class: 'btn btn-sm btn-primary' %>
          <%= link_to 'Delete', habit_reminder_path(@habit, reminder), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', habits_path %>
<%= link_to 'New Reminder', new_habit_reminder_path(@habit), class: 'btn btn-success' %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Back', habit_reminders_path(@habit) %>

app/views/reminders/show.html.erb
<div style="margin: 20px; padding: 20px; border: 1px solid #ccc; border-radius: 5px; background-color: #f9f9f9;">
  <h1 style="color: #333;">Reminder Details</h1>
  
  <p><strong>Frequency:</strong> <%= @reminder.frequency %></p>
  <p><strong>Habit:</strong> <%= @reminder.habit.name %></p>

  <ul style="list-style-type: none; padding: 0;">
  <li style="display: inline-block; margin-right: 10px;">
    <%= link_to "Edit", edit_habit_reminder_path(@reminder.habit, @reminder), class: 'btn btn-primary' %>
  </li>
  <li style="display: inline-block;">
    <%= link_to "Delete", habit_reminders_path(@reminder.habit, @reminder), method: :delete, data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?",
    }, class: 'btn btn-danger' %>
  </li>
</ul>


  <%= month_calendar(events: @reminder_events) do |date, events| %>
    <%= date %>
  
    <% events.each do |event| %>
      <%= render partial: 'event', locals: { event: event } %>
    <% end %>
  <% end %>
  

  <%= link_to 'Back', habit_reminders_path(@habit), class: 'btn btn-secondary' %>
</div>